ADDITIONAL_BUILD_PROPERTIES += \
    ro.rockstar.build.version=$(LINEAGE_VERSION) \
    ro.rockstar.display.version=$(LINEAGE_DISPLAY_VERSION) \
    ro.rockstar.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.modversion=$(ROCKSTAR_VERSION)

# Versioning
PRODUCT_VERSION_MAJOR = 10
ROCKSTAR_VERSION := 1.0

# Official and Unofficial builds
ifndef ROCKSTAR_BUILD_TYPE
ROCKSTAR_BUILD_TYPE := UNOFFICIAL
endif

# Packaging
LINEAGE_VERSION := RockstarROM-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d)-$(ROCKSTAR_BUILD_TYPE)-v$(ROCKSTAR_VERSION)
LINEAGE_DISPLAY_VERSION := RockstarROM-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(ROCKSTAR_BUILD_TYPE)-v$(ROCKSTAR_VERSION)
